name: ml3d_test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.2.2=py38_0
  - python=3.8.5=hcff3b4d_0
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py38_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.10.0
    - addict==2.2.1
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.21
    - future==0.18.2
    - future-fstrings==1.2.0
    - gast==0.3.3
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - idna==2.10
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - matplotlib==3.3.1
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.1.1
    - pillow==7.2.0
    - plyfile==0.7.2
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - six==1.15.0
    - sklearn==0.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torch==1.6.0
    - tqdm==4.48.2
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - wrapt==1.12.1

