dataset:
  name: ParisLille3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [65075320, 33014819, 656096, 61715, 296523, 4052947, 172132,4212295, 10599237]
  ignored_label_inds:
  - 0
  test_result_folder: ./test
  val_files:
  - Lille2.ply
  use_cache: True
  steps_per_epoch_train: 40
  steps_per_epoch_valid: 10
  sampler:
    name: SemSegSpatiallyRegularSampler
model:
  name: KPFCNN
  ckpt_path: # path/to/your/checkpoint
  KP_extent: 1.0
  KP_influence: linear
  aggregation_mode: sum
  architecture: [
  'simple',
  'resnetb',
  'resnetb_strided',
  'resnetb',
  'resnetb_strided',
  'resnetb_deformable',
  'resnetb_deformable_strided',
  'resnetb_deformable',
  'resnetb_deformable_strided',
  'resnetb_deformable',
  'nearest_upsample',
  'unary',
  'nearest_upsample',
  'unary',
  'nearest_upsample',
  'unary',
  'nearest_upsample',
  'unary']
  reduce_fc: true
  augment_color: 0.8
  augment_noise: 0.01
  augment_rotation: vertical
  augment_scale_anisotropic: true
  augment_scale_max: 1.1
  augment_scale_min: 0.9
  augment_symmetries:
  - true
  - false
  - false
  batch_limit: 20000
  grad_clip_norm: 100.0
  batch_norm_momentum: 0.98
  batcher: ConcatBatcher
  conv_radius: 2.5
  deform_fitting_mode: point2point
  deform_fitting_power: 1.0
  deform_radius: 6.0
  density_parameter: 5.0
  first_features_dim: 128
  first_subsampling_dl: 0.08
  fixed_kernel_points: center
  ignored_label_inds: [0]
  in_features_dim: 1
  in_points_dim: 3
  l_relu: 0.2
  in_radius: 4.0
  lbl_values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  min_in_points: 10000
  max_in_points: 17000
  modulated: false
  num_classes: 9
  num_kernel_points: 15
  num_layers: 5
  repulse_extent: 1.2
  use_batch_norm: true
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  momentum: 0.98
  batch_size: 1
  learning_rate: 0.01
  lr_decays: 0.98477
  deform_lr_factor: 0.1
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 5
  scheduler_gamma: 0.95
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
  weight_decay: 0.001
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
