dataset:
  name: S3DIS
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [3370714, 2856755, 4919229, 318158, 375640, 
  478001, 974733, 650464, 791496, 88727, 1284130, 229758, 2272837]
  ignored_label_inds: []
  num_points: 40960
  test_area_idx: 5
  test_result_folder: ./test
  use_cache: false
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: # path/to/your/checkpoint
  in_channels: 6
  blocks: [2, 2, 2, 2, 2]
  num_classes: 13
  voxel_size: 0.04
  max_voxels: 50000
  ignored_label_inds: [-1]
  augment:
    rotate:
      method: vertical
    scale:
      min_s: 0.95
      max_s: 1.05
    noise:
      noise_std: 0.005
    ChromaticAutoContrast:
      randomize_blend_factor: True
      blend_factor: 0.2
    ChromaticTranslation:
      trans_range_ratio: 0.05
    ChromaticJitter:
      std: 0.01
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.02
  momentum: 0.9
  weight_decay: 0.0001
  batch_size: 4
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 5
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 4
