dataset:
  name: ParisLille3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [53033221, 25821560,   546190, 54417,   
        180638,  3998129, 160899, 3441844, 9681606]
  ignored_label_inds:
  - 0
  num_points: 65536
  test_result_folder: ./test
  val_files:
  - Lille2.ply
  use_cache: true
  steps_per_epoch_train: 100
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 3
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 9
  num_layers: 5
  num_points: 65536
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
  weight_decay: 0.001
  t_augment:
    turn_on: false
    rotation_method: vertical
    scale_anisotropic: false
    symmetries: true
    noise_level: 0.01
    min_s: 0.9
    max_s: 1.1
  t_normalize:
    method: linear
    normalize_points: False
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.004
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 200
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 2
  train_sum_dir: train_log
  val_batch_size: 2
