dataset:
  name: Toronto3D
  cache_dir: ./logs/cache
  dataset_path: # path/to/your/dataset
  class_weights: [41697357, 1745448, 6572572, 19136493, 674897, 897825, 4634634, 374721]
  ignored_label_inds:
  - 0
  num_points: 65536
  prepro_grid_size: 0.06
  test_files:
  - L002.ply
  test_result_folder: ./test
  train_files:
  - L001.ply
  - L003.ply
  - L004.ply
  use_cache: true
  val_files:
  - L002.ply
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 6
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 8
  num_layers: 5
  num_points: 65536
  num_sub_points:
  - 16384
  - 4096
  - 1024
  - 256
  - 128
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
  weight_decay: 0
  t_augment:
    turn_on: false
    rotation_method: vertical
    scale_anisotropic: false
    symmetries: true
    noise_level: 0.01
    min_s: 0.5
    max_s: 2
  t_normalize:
    method: linear
    points_bias: 0
    points_scale: 1
    feat_bias: 0
    feat_scale: 255
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 10000
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
