dataset:
  name: Semantic3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache/
  class_weights: [5181602, 5012952, 6830086, 1311528, 10476365, 946982, 334860, 269353, 269353]
  ignored_label_inds:
  - 0
  num_points: 65536
  prepro_grid_size: 0.06
  test_result_folder: ./test
  use_cache: true
  val_split: 1
model:
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 6
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  name: RandLANet
  num_classes: 8
  num_layers: 5
  num_points: 65536
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 20
  scheduler_gamma: 0.95
  test_batch_size: 3
  train_sum_dir: train_log
  val_batch_size: 1
