dataset:
  name: ParisLille3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [65075320, 33014819, 656096, 61715, 296523, 4052947, 172132,4212295, 10599237]
  ignored_label_inds:
  - 0
  num_points: 65536
  prepro_grid_size: 0.06
  test_result_folder: ./test
  val_files:
  - Lille2.ply
  use_cache: true
  # steps_per_epoch_train: 1000
  # steps_per_epoch_valid: 100
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: #./logs/RandLANet_torch/checkpoint/ckpt_120.pth # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 3
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 9
  num_layers: 5
  num_points: 65536
  num_sub_points:
  - 16384
  - 4096
  - 1024
  - 256
  - 128
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
  weight_decay: 0.1
  t_augment:
    turn_on: true
    rotation_method: vertical
    scale_anisotropic: false
    symmetries: true
    noise_level: 0.01
    min_s: 0.5
    max_s: 2
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.0001
  main_log_dir: ./logs
  max_epoch: 10000
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
