dataset:
  name: Semantic3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache_small3d/
  class_weights: [5181602, 5012952, 6830086, 1311528, 10476365, 946982, 334860, 269353]
  ignored_label_inds:
  - 0
  num_points: 65536
  test_result_folder: ./test
  use_cache: true
  val_files:
  - bildstein_station1_xyz_intensity_rgb
  - domfountain_station1_xyz_intensity_rgb
  steps_per_epoch_train: 500
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 6
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 8
  num_layers: 5
  num_points: 65536
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
  t_normalize:
    method: linear
    feat_bias: 0
    feat_scale: 255
  t_augment:
    turn_on: true
    rotation_method: vertical
    scale_anisotropic: true
    symmetries: [true, false, false]
    noise_level: 0.001
    min_s: 0.8
    max_s: 1.2
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 2
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 5
  scheduler_gamma: 0.95
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
  test_compute_metric: false
